### PR TITLE
Fixing error in TIS camera; Adding support for allied vision cameras and GRBL boards

### PR DESCRIPTION
**Pull request by beniroquai**
This PR contains the one-liner fix for ensuring proper saving of the values in the TIS cameras. Besides that, a whole bunch of add-ons for the Allied Vision cameras and GRBL (i.e. CNC-boards) controls are included. Looks like a lot of cherry picking. Sorry for the bad code ;-)

### CODE REVIEW

**Comment by kasasxav** [comment]
Hi @beniroquai, please check the bullet points above when you have time (I edited).
I think would be nice to merge this into the main :)

**Comment by beniroquai** [comment]
Hey,  sorry for late reply. I was busy getting the devices ready for MiFoBio this year. Looks all good. We have a light-sheet and a multiwell platescanning device. I think there are tons of things one could do now :)..but one after another. 

I have updated the fork and hopefully worked on the issues you pointed out above. The recursive creation indeed was weird. I also just saw that last week. Was wondering why the UC2 config was missing after a fresh install on another machine. Indeed I changed the folder from Documents to something inside the Github root folder. Maybe not so smart? 
Also, how shall we keep it with the files? I for example added `pymba` to the pip install script, but perhaps this does not work on all the machines since the allied vision cameras only run on Windows/Ubuntu. Python bindings should be ok though.

What should I do now? Have not filed many PRs yet ;-)

**Comment by kasasxav** [comment]
Hey!

Thanks! There is another error now in `avcamera.py`, seems in the function in line 64 you refer to "gx" but it's not imported. Could you check it out?

Nice with MiFoBio! Congrats! I also saw your paper in open microscopy, very cool!

**Comment by kasasxav** [comment]
It also seems that the recursive files came back with your latest commit hehe

**Comment by kasasxav** [comment]
Also, I don't manage to find what you mean by adding `pymba`, could you help me find the file name and line? :)

**Comment by beniroquai** [comment]
> Also, I don't manage to find what you mean by adding `pymba`, could you help me find the file name and line? :)

`pymba` is just the python package for the Allied Vision cameras. I have added that to the `requierements.txt`
)


> Hey!
> 
> Thanks! There is another error now in `avcamera.py`, seems in the function in line 64 you refer to "gx" but it's not imported. Could you check it out?
> 
> Nice with MiFoBio! Congrats! I also saw your paper in open microscopy, very cool!

This I have solved. And also added "inoffical" Daheng Imaging support (i.e. `GXIPYManager`). I have not yet tested it, but will try it out as soon as I have the camera in my hands. This then refers to `gx`.




> It also seems that the recursive files came back with your latest commit hehe

Yes. That's very confusing. I tried explaining it in my latest issue :-)

Thanks!

**Pull request closed without merging**
